//CRIA UM PROJETO SPRING COM AS DEPENCENCIAS QUE APRENDEMOS:
//O PROJETO SERA FEITO PARA UMA BORRACHARIA:
//A BORRACHARIA TERÁ CLIENTE E ESSES CLIENTES TERÃO CARROS;
//ENTÃO DEVEMOS ARMAZENAR AS INFORMAÇÕES DE CLIENTE E DE CARROS, LEMBRANDO QUE O CARRO SERA ASSOCIADO
//AO CLIENTE.
//SOBE O CLIENTE QUERO O NOME, CPF, NUMERO TELEFONE, EMAIL
//SOBRE O CARRO QUERO AS INFORMAÇÕES DE MODELO, MARCA, ANO E QUAL SERVIÇO FOI EXECUTADO;
//TERA UMA TABELA DE SERVIÇO PRESTADO AO VEICULO, ESSA TABELA IRA ARMAZENAR AS INFORMAÇÕES DE
//VALOR, SERVICO PRESTADO, DATA E QUAL O CARRO FOI FEITO A MANUTENÇÃO
//QUERO QUE ENVIEI UM EMAIL QUANDO COM OS DADOS DO SERVIÇO QUE FORAM PRESTADO PARA O CLIENTE;
//VALOR DO SERVIÇO, DATA E O SERVIÇO EXECUTADO.
//QUERO UM RELATORIO COM O ULTIMOS 5 SERVIÇOS PRESTADOS, NESSE RELATORIO QUERO O NOME DO CLIENTE,
//MODELO DO CARRO, VALOR E O SERVICO PRESTADO.
//QUE OS JOGOS COMECEM !!!!!!!!!!!!!!!!
package org.serratec.backend.borracharia;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class BorrachariaApplication {

	public static void main(String[] args) {
		SpringApplication.run(BorrachariaApplication.class, args);
	}

}
